language: ruby
bundler_args: --without development
script:
  - bundle exec rake foodcritic
  - bundle exec rake knife
gemfile:
   - Gemfile
rvm:
  - 1.9.3
  - 2.0.0
env:
  - CHEF_VERSION=11.6
  - CHEF_VERSION=11.8
notifications:
  email:
      - jj.asghar@peopleadmin.com
